name: classificador_cafe_flutter_real
version: 1.0.0+1
description: Projeto real de classificacao de cafe com modelo TFLite

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  tflite: ^1.1.2
  collection: ^1.17.1
  permission_handler: ^11.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/modelo.tflite
    - assets/labels.txt
